Update pipeline.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -2,6 +2,11 @@ name: Tests Terraform
 
 on:
   workflow_dispatch:
+    inputs:
+      confirmation:
+        description: 'Confirmation to apply Terraform changes'
+        required: true
+        default: 'no'
   push:
     branches:
       - main
@@ -14,7 +19,7 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Azure login
-        run : az login
+        run: az login
         
       - name: Set up Terraform
         uses: hashicorp/setup-terraform@v1
@@ -32,14 +37,10 @@ jobs:
         
       - name: Confirm Apply
         run: |
-          if [ "$GITHUB_EVENT_NAME" == "push" ]; then
-            echo "Do you want to apply changes? (yes/no)"
-            read confirmation
-            if [ "$confirmation" != "yes" ]; then
-              echo "Terraform apply aborted."
-              exit 1
-            fi
+          if [ "${{ github.event.inputs.confirmation }}" != "yes" ]; then
+            echo "Terraform apply aborted."
+            exit 1
           fi
-
+          
       - name: Terraform Apply
         run: terraform apply
